### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by TJU-PanYizhe** [RALC88/riscv-vectorized-benchmark-suite#18]
blackscholes cannot open file.
Stuck here
![image](https://github.com/user-attachments/assets/d22da0e8-8ae7-4315-afbe-1c0f3c20701b)
![image](https://github.com/user-attachments/assets/77c25bdc-a631-44e3-916a-81b2895030e2)

**Comment by RALC88** [comment]
which branch ? please add more details.

**Comment by TJU-PanYizhe** [comment]
> which branch ? please add more details.

rvv-0p7 branch

**Comment by TJU-PanYizhe** [comment]
> which branch ? please add more details.

Thanks for replying

rvv-0p7 branch

command on x86 machine with qemu is `qemu-riscv64 -cpu c906fdv bin/blackscholes_serial.exe 1 "input/in_1.input" "output/out_1.output";`

command on riscv64 machine is `./blackscholes_serial.exe 1 ../input/in_1.input ../output/out_1.output`

**Comment by RALC88** [comment]
Could you try with Spike ?

**Comment by TJU-PanYizhe** [comment]
I'll try spike later. But why it fails on riscv machine

**Comment by RALC88** [comment]
I would say that because your command is wrong. I have not fully tested on qemu .
Contrary to spike where you can pass the arguments and it will recognize where the input file is, on qemu do you need to do extra steps to "mount" that file on the emulator´s file system. I will look into that since I am moving the suite to rvv1.0 (there is a new branch I created for it), and I am testing with Spike, gem5, and Qemu, however for those apps with input files, qemu does not find it. On Spike and Gem5 works.

**Comment by TJU-PanYizhe** [comment]
Okay, I understand the problem with qemu.

I've got a pure RISC-V environment(not run on qemu or simulated)
![image](https://github.com/user-attachments/assets/23994dcf-929a-48fd-b6ad-81f2243cb5da)

Got same error
![image](https://github.com/user-attachments/assets/14e62130-e742-4822-a944-fcc2d1b3250f)

**Comment by RALC88** [comment]
I successfully run the app. Not pretty what is the issue on your end.

I already updated to rvv-v1.0, now it is in master. It use the most updated toolchain.  I successfully tested in spike and gem5.
